### ISSUE TITLE
doesn't work in 4K resolution

### ISSUE THREAD

**Issue by selsie** [ryobg/sse-journal#2]
The size of the Journal is about 1/5th of the height and width of my screen. The menus are tiny too.

[![Bild journal-screenshotvukx9.jpg auf abload.de](https://abload.de/img/journal-screenshotvukx9.jpg)](https://abload.de/image.php?img=journal-screenshotvukx9.jpg)

**Comment by ryobg** [comment]
Have you tried to resize the book by dragging its corners? Have you tried to change the font scale as visible on top left part of the screen?

**Comment by ryobg** [comment]
As reported in: https://forums.nexusmods.com/index.php?showtopic=7662463/#entry80262153
